test_that("Statistic formula is correct",{expect_equal(round(ddsn(-0.5,2,2,2,0),4),1.054)})
test_that("Statistic formula is correct",{expect_equal(round(pdsn(-0.5,2,2,2,0),4),0.7734)})
test_that("Statistic formula is correct",{expect_equal(round(qdsn(0.5,2,2,2,0),4),-0.6823)})
test_that("An invalid number of parameters",{expect_error(rdsn())})
test_that("Statistic formula is correct",{expect_equal(round(deck(1,2,3),4),0.2307)})
test_that("Statistic formula is correct",{expect_equal(round(peck(1,2,3),4),0.9294)})
test_that("Statistic formula is correct",{expect_equal(round(qeck(0.1,1,1),4),-0.6084)})
test_that("An invalid number of parameters",{expect_error(reck())})
test_that("Statistic formula is correct",{expect_equal(round(den(1,1,2,2,2,1),4),0.2666)})
test_that("Statistic formula is correct",{expect_equal(round(pen(1,1,2,2,2,1),4),0.7279)})
test_that("Statistic formula is correct",{expect_equal(round(qen(0.5,1,2,2,2,1),4),0.291)})
test_that("An invalid number of parameters",{expect_error(ren())})
test_that("Statistic formula is correct",{expect_equal(round(dpc(0,1,2,2),4),0.1933)})
test_that("Statistic formula is correct",{expect_equal(round(ppc(0,1,2,2),4),0.4013)})
test_that("Statistic formula is correct",{expect_equal(round(qpc(0.5,1,2,2),4),1)})
test_that("An invalid number of parameters",{expect_error(rpc())})
test_that("Statistic formula is correct",{expect_equal(round(dspc(0,1,1,1,1,0),4),0.242)})
test_that("Statistic formula is correct",{expect_equal(round(pspc(0,1,1,1,1,0),4),0.8413)})
test_that("Statistic formula is correct",{expect_equal(round(qspc(0.5,1,1,1,1,0),4),-0.6823)})
test_that("An invalid number of parameters",{expect_error(rspc())})
test_that("Statistic formula is correct",{expect_equal(round(dtppn(2,1,1,1,2),4),0.4839)})
test_that("Statistic formula is correct",{expect_equal(round(ptppn(2,1,1,1,2),4),0.8413)})
test_that("Statistic formula is correct",{expect_equal(round(qtppn(0.5,1,1,1,2),4),1)})
test_that("An invalid number of parameters",{expect_error(rtppn())})


